In [1]:
import numpy as np;
import pandas as pd;

In [2]:
df =pd.read_csv("top_insta_influencers_data.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rank               200 non-null    int64
 1   channel_info       200 non-null    object
 2   influence_score    200 non-null    int64
 3   posts              200 non-null    object
 4   followers          200 non-null    object
 5   avg_likes          200 non-null    object
 6   60_day_eng_rate    200 non-null    object
 7   new_post_avg_like  200 non-null    object
 8   total_likes        200 non-null    object
 9   country            138 non-null    object
dtypes: int64(2), object(8)
memory usage: 15.8+ KB

In [4]:
df.describe()

             rank  influence_score
count  200.000000       200.000000
mean   100.500000        81.820000
std     57.879185         8.878159
min      1.000000        22.000000
25%     50.750000        80.000000
50%    100.500000        84.000000
75%    150.250000        86.000000
max    200.000000        93.000000

In [5]:
df.head()

,rank,channel_info,influence_score,posts,followers,avg_likes,60_day_eng_rate,new_post_avg_like,total_likes,country
0,1,cristiano,92,3.3k,475.8m,8.7m,1.39%,6.5m,29.0b,Spain
1,2,kyliejenner,91,6.9k,366.2m,8.3m,1.62%,5.9m,57.4b,United States
2,3,leomessi,90,0.89k,357.3m,6.8m,1.24%,4.4m,6.0b,NaN
3,4,selenagomez,93,1.8k,342.7m,6.2m,0.97%,3.3m,11.5b,United States
4,5,therock,91,6.8k,334.1m,1.9m,0.20%,665.3k,12.5b,United States

In [6]:
df.tail()

,rank,channel_info,influence_score,posts,followers,avg_likes,60_day_eng_rate,new_post_avg_like,total_likes,country
195,196,iambeckyg,71,2.3k,33.2m,623.8k,1.40%,464.7k,1.4b,United States
196,197,nancyajram,81,3.8k,33.2m,390.4k,0.64%,208.0k,1.5b,France
197,198,luansantana,79,0.77k,33.2m,193.3k,0.26%,82.6k,149.2m,Brazil
198,199,nickjonas,78,2.3k,33.0m,719.6k,1.42%,467.7k,1.7b,United States
199,200,raisa6690,80,4.2k,32.8m,232.2k,0.30%,97.4k,969.1m,Indonesia

In [7]:
df.columns

Index(['rank', 'channel_info', 'influence_score', 'posts', 'followers',
       'avg_likes', '60_day_eng_rate', 'new_post_avg_like', 'total_likes',
       'country'],
      dtype='object')

In [8]:
df.shape

(200, 10)

In [9]:
df.isnull().sum()

rank                  0
channel_info          0
influence_score       0
posts                 0
followers             0
avg_likes             0
60_day_eng_rate       0
new_post_avg_like     0
total_likes           0
country              62
dtype: int64

In [18]:
df.sort_values(by="influence_score", ascending=False)

,rank,channel_info,influence_score,posts,followers,avg_likes,60_day_eng_rate,new_post_avg_like,total_likes,country
3,4,selenagomez,93,1.8k,342.7m,6.2m,0.97%,3.3m,11.5b,United States
0,1,cristiano,92,3.3k,475.8m,8.7m,1.39%,6.5m,29.0b,Spain
20,21,katyperry,92,2.0k,170.3m,715.0k,0.16%,265.1k,1.5b,NaN
6,7,arianagrande,92,5.0k,327.7m,3.7m,1.20%,3.9m,18.4b,United States
7,8,beyonce,92,2.0k,272.8m,3.6m,0.76%,2.0m,7.4b,United States
...,...,...,...,...,...,...,...,...,...,...
174,175,nattinatasha,47,0.03k,35.9m,518.1k,0.80%,285.9k,18.7m,Czech Republic
76,77,karimbenzema,42,2.0k,56.9m,878.5k,1.62%,918.9k,1.8b,Spain
127,128,maisa,42,1.5k,44.5m,553.0k,0.67%,294.1k,820.1m,Brazil
193,194,zidane,41,0.37k,33.5m,1.1m,1.61%,532.7k,391.9m,France
93,94,mosalah,22,0.84k,52.5m,1.8m,2.18%,1.1m,1.5b,NaN

In [14]:
df.columns

Index(['rank', 'channel_info', 'influence_score', 'posts', 'followers',
       'avg_likes', '60_day_eng_rate', 'new_post_avg_like', 'total_likes',
       'country'],
      dtype='object')

In [17]:

df.groupby("country")["followers"].sum().sort_values(ascending=False).head()

country
United Kingdom                                 85.9m59.6m54.1m39.9m
India             70.4m68.9m68.7m68.4m66.3m62.7m55.6m53.5m50.2m4...
Uruguay                                                       66.9m
Turkey                                                   66.2m42.1m
Indonesia                       63.5m52.4m48.9m40.0m38.8m36.9m32.8m
Name: followers, dtype: object

In [21]:
print(df[df["country"] == "India"])

     rank       channel_info  influence_score  posts followers avg_likes  \
46     47         nehakakkar               84   2.3k     70.4m      1.5m
50     51       narendramodi               85  0.54k     68.9m      2.9m
51     52         aliaabhatt               82   1.8k     68.7m      1.8m
52     53    deepikapadukone               83  0.26k     68.4m      1.6m
57     58        katrinakaif               85   1.0k     66.3m      1.7m
67     68     jacquelinef143               85   2.4k     62.7m      1.1m
78     79             karolg               83   3.3k     55.6m      3.1m
86     87    beingsalmankhan               76   1.2k     53.5m      1.4m
99    100         kritisanon               76   2.7k     50.2m    897.2k
131   132           varundvn               84   1.9k     43.8m      1.1m
176   177  tigerjackieshroff               83   2.1k     35.6m      1.1m
194   195        sonamkapoor               75   4.8k     33.3m    264.7k

    60_day_eng_rate new_post_avg_like total_likes country
46            0.54%            370.1k        3.5b   India
50            3.01%              2.0m        1.6b   India
51            3.14%              2.1m        3.3b   India
52            2.23%              1.5m      419.0m   India
57            2.25%              1.5m        1.7b   India
67            1.15%            718.8k        2.8b   India
78           10.25%              5.7m       10.1b   India
86            1.33%            693.9k        1.6b   India
99            1.21%            604.4k        2.4b   India
131           1.48%            640.5k        2.0b   India
176           1.20%            422.9k        2.2b   India
194           0.63%            209.2k        1.3b   India

In [22]:
df["country"].value_counts()["India"]

np.int64(12)